### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by isenscwadorf** [daswer123/xtts-api-server#30]
I have tried multiple time to install on windows and I get this error message

```
building`` 'TTS.tts.utils.monotonic_align.core' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for tts
Building wheel for mojimoji (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for mojimoji (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [11 lines of output]
running bdist_wheel
running build
running build_py
creating build
creating build\lib.win-amd64-cpython-311
creating build\lib.win-amd64-cpython-311\mojimoji
copying mojimoji_init_.pyi -> build\lib.win-amd64-cpython-311\mojimoji
copying mojimoji\py.typed -> build\lib.win-amd64-cpython-311\mojimoji
running build_ext
building 'mojimoji' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for mojimoji
Failed to build tts mojimoji
ERROR: Could not build wheels for tts, mojimoji, which is required to install pyproject.toml-based projects
``` 

I already installed Microsoft Visual C++

**Comment by daswer123** [comment]
Hi you need to install microsoft buiilders tools 2019 with c++ development package
https://aka.ms/vs/17/release/vs_BuildTools.exe

![image](https://github.com/daswer123/xtts-api-server/assets/22278673/aaa1e5bf-3977-4907-832e-4a281ca627f1)

**Comment by PhytonGitter** [comment]
Hi, i also have the Problem and i installed microsoft builders tools with c++ development package. The Problem is still there.
![grafik](https://github.com/daswer123/xtts-api-server/assets/77126190/28035770-3982-455b-b526-4ce67208c5ab)

`      copying TTS\vocoder\utils\generic_utils.py -> temp_build\TTS\vocoder\utils
      running build_ext
      building 'TTS.tts.utils.monotonic_align.core' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tts
  Building wheel for encodec (setup.py) ... done
  Created wheel for encodec: filename=encodec-0.1.1-py3-none-any.whl size=45824 sha256=385077de1853865c1546376b6155238d22a160b7bb8267c215c38cb246611401
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\1d\9d\20\489d6aafffb505e18fcfcfbe722562f91c26af0a8a6da7d00b
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.5-py3-none-any.whl size=86944 sha256=237c10020d13a82b93d69218429089a516e938ead13fd9b270e0629446338773
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\0f\01\17\26951217a11fb724b7027c6dd5b620b6d368104f7e6d4171fc
  Building wheel for bnnumerizer (setup.py) ... done
  Created wheel for bnnumerizer: filename=bnnumerizer-0.0.2-py3-none-any.whl size=5293 sha256=a368a0d660439b6c33a6b7889b72245a1f2764c9ff7a6775f549291b4e3a77d7
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\cf\2f\42\a7c0e5bc7281b2e1b7bdfbd08d8220010b6df91ffdcfb571e7
  Building wheel for bnunicodenormalizer (setup.py) ... done
  Created wheel for bnunicodenormalizer: filename=bnunicodenormalizer-0.1.6-py3-none-any.whl size=22858 sha256=752844262f21564117205e5bb4d4a99fe37140404df900b101ca6ffe2aa6e96d
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\e9\d8\cc\b2809f6116dc25b5b0e888b673eac1363b50888004ca43925a
  Building wheel for jaconv (setup.py) ... done
  Created wheel for jaconv: filename=jaconv-0.3.4-py3-none-any.whl size=16444 sha256=3dd39f4f8abc2c9b504b018d922a99d85ba8cac4ad7f3e59c90bf20534e42332
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\49\de\f1\55f605920db3666d30215331bc85f24686dde9b95b473ae41b
  Building wheel for jieba (setup.py) ... done
  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314494 sha256=fc0ac9e1e73c6b8e5a1a514584377164fee23738d99908bc91706cf50ee13f29
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\7d\74\cf\08c94db4b784e2c1ef675a600b7b5b281fd25240dcb954ee7e
  Building wheel for unidic-lite (setup.py) ... done
  Created wheel for unidic-lite: filename=unidic_lite-1.0.8-py3-none-any.whl size=47658853 sha256=7aa3f01223d3cf80ce2a59f43907f7725e344b5249cb532110c74fc05031a521
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\56\9c\4f\2c115e896b4b6c584039ca19de3581d333856782ef108cdc5c
  Building wheel for docopt (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13793 sha256=dc383fddc932280974ddc03a4290a8696cee0e7cbc319c8620125977e4d2abbf
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\70\4a\46\1309fc853b8d395e60bafaf1b6df7845bdd82c95fd59dd8d2b
  Building wheel for gruut-ipa (setup.py) ... done
  Created wheel for gruut-ipa: filename=gruut_ipa-0.13.0-py3-none-any.whl size=104931 sha256=57ed219d24954f1a18e995249d590f3f5263ded22fb95e4496904abe76a5b940
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\ab\22\10\9d98cfd0277a5876d450ca23902ecd0a41a5473efdcf309e6e
  Building wheel for gruut_lang_de (setup.py) ... done
  Created wheel for gruut_lang_de: filename=gruut_lang_de-2.0.0-py3-none-any.whl size=18498212 sha256=5ec35e2626ca6a3fc69340ec4d9e47744d7ce5669eda8b84e68f120768fb34a3
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\b7\dc\3d\825e41f38b3d3161751f97c0a0b65d0cd95a5a4702a883c8f9
  Building wheel for gruut_lang_en (setup.py) ... done
  Created wheel for gruut_lang_en: filename=gruut_lang_en-2.0.0-py3-none-any.whl size=15297208 sha256=c013921308b9dcd95ef876dff8c7075fb5ea83ab959ead4036a504dc6b98d2e4
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\c0\29\5b\957782ce4d196eb0a6315836def9d7761ae85825a5747bcc97
  Building wheel for gruut_lang_es (setup.py) ... done
  Created wheel for gruut_lang_es: filename=gruut_lang_es-2.0.0-py3-none-any.whl size=32173825 sha256=40d72b09d8db03efff8032aeacab01ba4cea1a718eedf5fb3aca1500f2baea37
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\90\1a\58\a7792597ba8254a78d417f00221962be7e47420b489a010e62
  Building wheel for gruut_lang_fr (setup.py) ... done
  Created wheel for gruut_lang_fr: filename=gruut_lang_fr-2.0.2-py3-none-any.whl size=10968796 sha256=abfe9e0adc5ead4e8df2f991f9883e76c2a53a17c2fa41b36181991a061e7495
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\ef\0c\63\ff8472d618329f72f6f645e85e4e1584ea1dd4cb9c0fc2fc06
  Building wheel for gruut (setup.py) ... done
  Created wheel for gruut: filename=gruut-2.2.3-py3-none-any.whl size=75872 sha256=38f966863318f680cb7141b2e52509cb26a37f318860e1f4bf438c3f6ec49226
  Stored in directory: c:\users\kevin\appdata\local\pip\cache\wheels\2e\9c\b4\a963ba6c181aa3d65370c3aa40c420a249ff02cef4c724c071
Successfully built encodec umap-learn bnnumerizer bnunicodenormalizer jaconv jieba unidic-lite docopt gruut-ipa gruut_lang_de gruut_lang_en gruut_lang_es gruut_lang_fr gruut
Failed to build tts
ERROR: Could not build wheels for tts, which is required to install pyproject.toml-based projects`

**Comment by daswer123** [comment]
> copying TTS\vocoder\utils\generic_utils.py -> temp_build\TTS\vocoder\utils
>       running build_ext
>       building 'TTS.tts.utils.monotonic_align.core' extension
>       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>       [end of output]

You may not have it in the paths, try rebooting the computer and try again

**Comment by PhytonGitter** [comment]
It does now work after i completely uninstalled Visual studio and all BuildTools and all Visual C++ versions and after that installing the buildtools. I am confused but it works now. :D

**Comment by IncognitoAnkh** [comment]
I have the same problem, I already tried uninstalling all my build tools and dev packages, reinstalling the build tools with the c++ development package, added buildtools to the path manually, installed cmake (I heard it works with this problem but... not for me), I tried using venv and conda, using the x64 native tools command prompt and regular cmd, again no luck (obviously rebooted my system after each attempt).

My last attempt was to copy the 2 problematic libraries (tts and mojimoji) from a previous installation (12/07/2023) and paste them into the new one. (My Env/Lib/site-packages), all of this on a conda environment, this worked and all remaining requirements were installed successfully,

The version from 12/07/2023 didn't give me any problems during the installation process so this is an issue related to the latest versions.
